// AUTO-GENERATED by scripts/generate-gdrive-secrets.mjs — do not edit by hand.
// The committed copy holds EMPTY placeholders; desktop release builds overwrite
// it from the GDRIVE_DESKTOP_CLIENT_ID / GDRIVE_DESKTOP_CLIENT_SECRET env vars.
// NEVER commit real values here — this repo is public.
//
// Only the Tauri desktop (loopback Auth-Code + PKCE) flow uses these; the web
// build leaves them empty (the browser GIS flow needs no secret).

export interface DesktopOAuth {
	readonly clientId: string;
	readonly clientSecret: string;
}

export const DESKTOP_OAUTH: DesktopOAuth = {
	clientId: '',
	clientSecret: '',
};
