/**
 * Map of Lucide icon names to their Angular component classes.
 *
 * This is used for dynamic rendering in the icon picker grid and
 * note toolbar, where we don't know the icon at compile time.
 *
 * The key is the kebab-case name (e.g. "file-text") — matches
 * the form stored in frontmatter after "lucide:" prefix.
 *
 * To add an icon: import the LucideXxx class and add an entry.
 */

/* eslint-disable @typescript-eslint/no-deprecated */

import { Type } from '@angular/core';
import {
	LucideAlarmClock,
	LucideAlarmClockCheck,
	LucideAlertCircle,
	LucideAlertTriangle,
	LucideArchive,
	LucideArchiveRestore,
	LucideArrowDown,
	LucideArrowLeft,
	LucideArrowRight,
	LucideArrowUp,
	LucideAtSign,
	LucideAward,
	LucideBell,
	LucideBellOff,
	LucideBook,
	LucideBookOpen,
	LucideBookmark,
	LucideBookmarkCheck,
	LucideBrush,
	LucideCalendar,
	LucideCalendarCheck,
	LucideCalendarDays,
	LucideCalendarPlus,
	LucideCamera,
	LucideCheck,
	LucideCheckCircle,
	LucideCheckSquare,
	LucideChevronDown,
	LucideChevronLeft,
	LucideChevronRight,
	LucideChevronUp,
	LucideCircle,
	LucideCircleDot,
	LucideCircleHelp,
	LucideClipboard,
	LucideClipboardCheck,
	LucideClipboardCopy,
	LucideClipboardList,
	LucideClipboardPaste,
	LucideClipboardPen,
	LucideClock,
	LucideCloud,
	LucideCloudLightning,
	LucideCloudMoon,
	LucideCloudRain,
	LucideCloudSnow,
	LucideCloudSun,
	LucideCode,
	LucideCodeXml,
	LucideCompass,
	LucideDatabase,
	LucideDiamond,
	LucideDot,
	LucideDroplets,
	LucideEraser,
	LucideExpand,
	LucideExternalLink,
	LucideEye,
	LucideEyeOff,
	LucideFileArchive,
	LucideFileCode,
	LucideFileEdit,
	LucideFileImage,
	LucideFileJson,
	LucideFilePen,
	LucideFilePlus,
	LucideFileSearch,
	LucideFileSpreadsheet,
	LucideFileText,
	LucideFileType,
	LucideFlag,
	LucideFlame,
	LucideFolder,
	LucideFolderOpen,
	LucideFolderPlus,
	LucideFolderTree,
	LucideGitBranch,
	LucideGitCommit,
	LucideGitPullRequest,
	LucideGlobe,
	LucideHammer,
	LucideHardDrive,
	LucideHash,
	LucideHeart,
	LucideHeartPulse,
	LucideHighlighter,
	LucideHome,
	LucideHourglass,
	LucideImage,
	LucideImages,
	LucideInfo,
	LucideKey,
	LucideLaptop,
	LucideLibrary,
	LucideLink,
	LucideLock,
	LucideLockOpen,
	LucideMail,
	LucideMailOpen,
	LucideMap,
	LucideMapPin,
	LucideMaximize,
	LucideMedal,
	LucideMessageCircle,
	LucideMessageSquare,
	LucideMessageSquarePlus,
	LucideMessagesSquare,
	LucideMinimize,
	LucideMinus,
	LucideMinusCircle,
	LucideMonitor,
	LucideMoon,
	LucideMove,
	LucideMusic,
	LucideNotebook,
	LucideNotebookPen,
	LucideNotebookText,
	LucidePaintbrush,
	LucidePalette,
	LucidePen,
	LucidePenLine,
	LucidePenTool,
	LucidePencil,
	LucidePlay,
	LucidePlus,
	LucidePlusCircle,
	LucideScissors,
	LucideScroll,
	LucideScrollText,
	LucideSearch,
	LucideSend,
	LucideServer,
	LucideSettings,
	LucideShare,
	LucideShrink,
	LucideSlidersHorizontal,
	LucideSmartphone,
	LucideSnowflake,
	LucideSquare,
	LucideStar,
	LucideStickyNote,
	LucideSun,
	LucideTablet,
	LucideTag,
	LucideTarget,
	LucideTerminal,
	LucideTimer,
	LucideTimerReset,
	LucideTrash2,
	LucideTriangle,
	LucideTrophy,
	LucideUser,
	LucideUserPlus,
	LucideUsers,
	LucideWaves,
	LucideWifi,
	LucideWind,
	LucideWrench,
	LucideX,
	LucideXCircle,
	LucideZoomIn,
	LucideZoomOut,
} from '@lucide/angular';

/**
 * Lookup map from kebab-case name to Lucide Angular component class.
 * Used by DynamicLucideIconComponent for runtime rendering.
 */
export const LUCIDE_COMPONENT_MAP: ReadonlyMap<string, Type<unknown>> = new Map<
	string,
	Type<unknown>
>([
	['alarm-clock', LucideAlarmClock],
	['alarm-clock-check', LucideAlarmClockCheck],
	['alert-circle', LucideAlertCircle],
	['alert-triangle', LucideAlertTriangle],
	['archive', LucideArchive],
	['archive-restore', LucideArchiveRestore],
	['arrow-down', LucideArrowDown],
	['arrow-left', LucideArrowLeft],
	['arrow-right', LucideArrowRight],
	['arrow-up', LucideArrowUp],
	['at-sign', LucideAtSign],
	['award', LucideAward],
	['bell', LucideBell],
	['bell-off', LucideBellOff],
	['book', LucideBook],
	['book-open', LucideBookOpen],
	['bookmark', LucideBookmark],
	['bookmark-check', LucideBookmarkCheck],
	['brush', LucideBrush],
	['calendar', LucideCalendar],
	['calendar-check', LucideCalendarCheck],
	['calendar-days', LucideCalendarDays],
	['calendar-plus', LucideCalendarPlus],
	['camera', LucideCamera],
	['check', LucideCheck],
	['check-circle', LucideCheckCircle],
	['check-square', LucideCheckSquare],
	['chevron-down', LucideChevronDown],
	['chevron-left', LucideChevronLeft],
	['chevron-right', LucideChevronRight],
	['chevron-up', LucideChevronUp],
	['circle', LucideCircle],
	['circle-dot', LucideCircleDot],
	['circle-help', LucideCircleHelp],
	['clipboard', LucideClipboard],
	['clipboard-check', LucideClipboardCheck],
	['clipboard-copy', LucideClipboardCopy],
	['clipboard-list', LucideClipboardList],
	['clipboard-paste', LucideClipboardPaste],
	['clipboard-pen', LucideClipboardPen],
	['clock', LucideClock],
	['cloud', LucideCloud],
	['cloud-lightning', LucideCloudLightning],
	['cloud-moon', LucideCloudMoon],
	['cloud-rain', LucideCloudRain],
	['cloud-snow', LucideCloudSnow],
	['cloud-sun', LucideCloudSun],
	['code', LucideCode],
	['code-xml', LucideCodeXml],
	['compass', LucideCompass],
	['database', LucideDatabase],
	['diamond', LucideDiamond],
	['dot', LucideDot],
	['droplets', LucideDroplets],
	['eraser', LucideEraser],
	['expand', LucideExpand],
	['external-link', LucideExternalLink],
	['eye', LucideEye],
	['eye-off', LucideEyeOff],
	['file-archive', LucideFileArchive],
	['file-code', LucideFileCode],
	['file-edit', LucideFileEdit],
	['file-image', LucideFileImage],
	['file-json', LucideFileJson],
	['file-pen', LucideFilePen],
	['file-plus', LucideFilePlus],
	['file-search', LucideFileSearch],
	['file-spreadsheet', LucideFileSpreadsheet],
	['file-text', LucideFileText],
	['file-type', LucideFileType],
	['flag', LucideFlag],
	['flame', LucideFlame],
	['folder', LucideFolder],
	['folder-open', LucideFolderOpen],
	['folder-plus', LucideFolderPlus],
	['folder-tree', LucideFolderTree],
	['git-branch', LucideGitBranch],
	['git-commit', LucideGitCommit],
	['git-pull-request', LucideGitPullRequest],
	['globe', LucideGlobe],
	['hammer', LucideHammer],
	['hard-drive', LucideHardDrive],
	['hash', LucideHash],
	['heart', LucideHeart],
	['heart-pulse', LucideHeartPulse],
	['highlighter', LucideHighlighter],
	['home', LucideHome],
	['hourglass', LucideHourglass],
	['image', LucideImage],
	['images', LucideImages],
	['info', LucideInfo],
	['key', LucideKey],
	['laptop', LucideLaptop],
	['library', LucideLibrary],
	['link', LucideLink],
	['lock', LucideLock],
	['lock-open', LucideLockOpen],
	['mail', LucideMail],
	['mail-open', LucideMailOpen],
	['map', LucideMap],
	['map-pin', LucideMapPin],
	['maximize', LucideMaximize],
	['medal', LucideMedal],
	['message-circle', LucideMessageCircle],
	['message-square', LucideMessageSquare],
	['message-square-plus', LucideMessageSquarePlus],
	['messages-square', LucideMessagesSquare],
	['minimize', LucideMinimize],
	['minus', LucideMinus],
	['minus-circle', LucideMinusCircle],
	['monitor', LucideMonitor],
	['moon', LucideMoon],
	['move', LucideMove],
	['music', LucideMusic],
	['notebook', LucideNotebook],
	['notebook-pen', LucideNotebookPen],
	['notebook-text', LucideNotebookText],
	['paintbrush', LucidePaintbrush],
	['palette', LucidePalette],
	['pen', LucidePen],
	['pen-line', LucidePenLine],
	['pen-tool', LucidePenTool],
	['pencil', LucidePencil],
	['play', LucidePlay],
	['plus', LucidePlus],
	['plus-circle', LucidePlusCircle],
	['scissors', LucideScissors],
	['scroll', LucideScroll],
	['scroll-text', LucideScrollText],
	['search', LucideSearch],
	['send', LucideSend],
	['server', LucideServer],
	['settings', LucideSettings],
	['share', LucideShare],
	['shrink', LucideShrink],
	['sliders-horizontal', LucideSlidersHorizontal],
	['smartphone', LucideSmartphone],
	['snowflake', LucideSnowflake],
	['square', LucideSquare],
	['star', LucideStar],
	['sticky-note', LucideStickyNote],
	['sun', LucideSun],
	['tablet', LucideTablet],
	['tag', LucideTag],
	['target', LucideTarget],
	['terminal', LucideTerminal],
	['timer', LucideTimer],
	['timer-reset', LucideTimerReset],
	['trash-2', LucideTrash2],
	['triangle', LucideTriangle],
	['trophy', LucideTrophy],
	['user', LucideUser],
	['user-plus', LucideUserPlus],
	['users', LucideUsers],
	['waves', LucideWaves],
	['wifi', LucideWifi],
	['wind', LucideWind],
	['wrench', LucideWrench],
	['x', LucideX],
	['x-circle', LucideXCircle],
	['zoom-in', LucideZoomIn],
	['zoom-out', LucideZoomOut],
]);
