// AUTO-GENERATED by scripts/generate-build-info.mjs — do not edit by hand.
// The committed copy holds dev placeholders; production builds overwrite it.

export interface BuildInfo {
	readonly version: string;
	readonly gitSha: string;
	/** ISO-8601 build timestamp, or '' for an un-stamped dev build. */
	readonly builtAt: string;
}

export const BUILD_INFO: BuildInfo = {
	version: '0.1.5',
	gitSha: '110417e',
	builtAt: '2026-06-30T20:28:43.943Z',
};
