// AUTO-GENERATED by scripts/generate-build-info.mjs.
// This committed copy holds dev placeholders; production builds overwrite it
// with the real version, git SHA, and timestamp. Safe to edit by hand only for
// the placeholder values below.

export interface BuildInfo {
	readonly version: string;
	readonly gitSha: string;
	/** ISO-8601 build timestamp, or '' for an un-stamped dev build. */
	readonly builtAt: string;
}

export const BUILD_INFO: BuildInfo = {
	version: '0.1.2',
	gitSha: 'dev',
	builtAt: '',
};
